### ISSUE TITLE
Issue when trying to color the Items

### ISSUE THREAD

**Issue by N0cturio** [Zerthick/ColorAnvil#2]
When putting an item in the anvil , for exemple an item called "Parrot" and renaming it like "&4Parrot", the item is going out of the anvil renamed as "&4Parrot".

Spongeforge version : 7.1.0-BETA-3206

**Comment by Zerthick** [comment]
This appears to be a bug with Sponge itself, I've created an issue for it here: https://github.com/SpongePowered/SpongeCommon/issues/2043

**Comment by Zerthick** [comment]
Fixed in version [1.2.0](https://github.com/Zerthick/ColorAnvil/releases/tag/v1.2.0)! Be sure to update Sponge or it won't work.
